### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by nwillemse** [mhallsmoore/qstrader#1]
Hi Michael,

Looks like settings.py.example and __init__.py is missing from the root directory.

Also, import queue statement doesn't work in the execution_handler.py file.

Thanks

**Comment by mhallsmoore** [comment]
Hi nwillemse,

Thanks for pointing out these issues.

I'll add __init__.py and an example settings.py to the root directory.

Also, I think it is likely that you might be using Python 2.7.x, which is why the "import queue" line doesn't work. I'll amend the code to be both 2.7.x and 3.5.x compatible, as at the moment it is only tested for Python 3.

I'll close the issue when it's done.

Thanks,

Mike.

**Comment by nwillemse** [comment]
Hi Michael,

Could you commit the __init__.py file in the root directory?  I think it's causing issues for new users trying the software.

Thanks
Nick

**Comment by mhallsmoore** [comment]
Hi Nick,

This has now been added.

Mike.
