### ISSUE TITLE
Logging bar timestamp, in compliance. 

### ISSUE THREAD

**Issue by muke5hy** [mhallsmoore/qstrader#110]
I am trying to log transaction in compliance, but I noticed the timestamp which is being passed .
How we can get actual time of bar/tick. 

``` python
class IBSimulatedExecutionHandler(AbstractExecutionHandler):

    def execute_order(self, event):
         timestamp = self.price_handler.get_last_timestamp(event.ticker)

```

In above code we are passing last_timestamp. What is use case of passing get_last_timestamp?

**Comment by ryankennedyio** [comment]
`get_last_timestamp` is there because the Event passed into the ExecutionHandler does not provide a timestamp -- we must look it up historically. If it weren't for this, none of the events from a backtest would be logged with time.

If you would like to also log the full event that causes a strategy to create a Signal, I would suggest creating your own `Compliance` module (basically just copy the current one and add one extra method, `log_signal()`), and have your `Strategy` call that method with anything extra you would like to log.

Would that roughly achieve what you're looking for? Technically speaking, the ExecutionHandler should not log the time of a tick -- it should log the time that an order was actually _executed_. In practice this is probably a few ms after the tick, plus network latency. Just be aware that the `SignalEvent` created by your strategy may not actually be executed, if for example, your `RiskManager` decides not to allow the suggested position.

**Comment by muke5hy** [comment]
I do not want to log the signal time but the trade time, which I think should be very close to signal time. 
Looking into timestamp of ExecutionHandler that's not a the time should be logged. As it always gives first bar time of minute data. 

#109 should certainly solve the problem.
