### ISSUE TITLE
Feature/discussion: OHCLV Bars?

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#12]
I'm not sure that IB allows tick-by-tick data in a backtest, and there's currently no provisioning in `qstrader` for Volume (but that itself should be pretty easy).

I think it would be useful if the system would "roll up" streamed tick data into OHCLV bars of a particular duration before they are analysed by a Strategy. It wouldn't make sense to inundate 1hr+ timeframe strategies with loads and loads of tick-data when they only care about checking things over 5m+

Would this be useful & which part of the system should be responsible for doing this? It would make sense to me that a price_handler should do this, and then the `TickEvent`s that go through the main loop would simply be the OHCLV bars, rather than just Ticks.

**Comment by mhallsmoore** [comment]
Hi Ryan,

Indeed, there's currently no consideration for Volume as of yet (since that needs to be measured over a time period). 

Your idea of OHLVC bars is a good idea. I've actually been working on a basic YahooFinancePriceHandler that does roughly what you describe, albeit without the "rolling up" of the data.

Rolling up, or binning, of tick data is actually quite subtle, so it would need to be given a lot of thought. For instance, if there are no ticks in a particular period (possible for some small-cap equities), then we have to decide what to do regarding the OHLC values, e.g. do we set them all to the last closing value? 

What we need to be careful of is assuming that it would be easy to achieve a price value equivalent to the last "close" over a long period of no ticks. 

I think for the time being it makes sense to utilise OHLCV data that has already been binned by an external vendor and be aware of their binning mechanism when trading. For instance, I would like to include IQFeed, QuantQuote and Quandl data into QSTrader as time progresses.

I also agree that a PriceHandler class is the best place for this, although we might wish to include another event type, i.e. OHLCVEvent, which gets directed specifically to an PriceHandlerOHLVC type object.

What do you think?

**Comment by ryankennedyio** [comment]
Hey Mike,

I was thinking the exact same thing about OHCLVEvent, as there's much more information to include in a bar than a raw TickEvent. That also gives us a really nice place to include Volume data, minimal extra code. I imagine this would make it fairly straightforward to build momentum breakout type strategies, for example.

If IQ, QuantQuote and Quandl all share similar enough data formats, I'm sure we can have every price handler either emit a TickEvent or OHCLVEvent for the rest of the system, which is a nice abstraction. Maybe OHCLVEvent can even extend from TickEvent, for code-reuse. I haven't looked into those providers to see what they do for "empty" timeframes, but all the charting software I've used just leaves blank bars for those fun illiquid speccies, which feels pretty natural. Haven't thought enough about what kind of issues that will create though.

After thinking for a few days on it, I also agree that ticks should be rolled up in the price handler, or externally to QStrader. Much more plug-and-play that way. That also actually fits in perfectly to what I'm thinking of for my personal C/ZeroMQ price handler, if I end up going that way.

**Comment by nwillemse** [comment]
Hi,

I'm also thinking about this OHLC bars and how to implement it.  Maybe BarEvent instead of OHLCVEvent.

Mike, relating to this, how should we handle get_latest_bar_close(), etc methods to get the last n bar of prices to calculate indicators for generating signals.  You have something similar in the old ATS backtester?  At some stage the live tick data needs to merge with the historical data when producing bar data.  Any ideas on how to best implement this would be helpful.

I have started working on a sqlite_price_handler to read the OHLC bar data from my sqlite database.  However, right now I just stream the close as a tick event, but maybe I need to stream a new BarEvent instead...

Nick

**Comment by ryankennedyio** [comment]
BarEvent is probably a better name. I'll probably work on this feature next, because a strategy I want to explore depends on volume.

I see the data that each BarEvent would need are:

- Open
- High
- Low
- Close
- Volume
- Opening Timestamp
- Closing Timestamp

Looking at previous bars will be interesting. Say we're doing a simple MACD strategy, I believe the `Strategy` itself should hold enough historical data for it to calculate it's own signals... So the `Strategy` might have a dict of 200 tickers we're interested in, and each ticker-index contains enough historical data to make the buy/sell signal decision. I think keeping the "last N bars" elsewhere in the system might get messy?




Regarding live tick data merging to historical/bars -- I think your live `price_handler` will have to "roll up" ticks that come in, and place a relevant BarEvent into the queue when it is ready.

**Comment by dieterjansen** [comment]
I was thinking about these sorts of issues the other day while messing about with QSForex - the following paper has some ideas that may be applicable:
 
    http://www.eckner.com/papers/ts_alg.pdf

**Comment by hpsilva** [comment]
Hi everyone!

I am happy to find that things are heating up and getting traction here on QStrader, and i would like to contribute as well, soon i have some free time.

I would like propose including at least a measure of spread on the historical data. I never really worked with IB, so i don't know exactly how how it looks like their historical data feed and bid/ask info is available, or only midpoint based candles.
However taking the example of Oanda for instance, you get OHLC from either bid and ask sides.
This is particularly useful for evaluating more realistically trading costs, eventually control trading when spread goes out of certain range, etc, etc.

Actually Oanda could be another useful source of historical data, as it is very easy to pull it from their API, and i can contribute with this part of code, soon the bar event is settled down?

Cheers!

**Comment by hpsilva** [comment]
Just another thing which might be useful for this discussion, that eventually you are not aware of.
oanda-trading-environment (@hootnoot) provides with a neat implementation of a "candle factory" API, storage, etc. In one hand it listens to the broker websocket, on the other hand it distributes binned bar information thru an internal web socket (zmq) to as many strategies as desired. It might be interesting for you to have a look, as it seems to me is similar to what you are looking for to implement.

On my own application i ended implementing a more passive approach just puling data on a fixed time basis ( x second resolution), as i don't find of use yet to look at tick or bar data in my strategies.

About data handling inside a strategy, i have done it on an object oriented fashion like this:
* On strategy initialization, historical data is pulled from the API for each instrument traded, within the necessary range;
* Start listening to live data;
* New incoming observations are added to data frame;
* Signal check based on new data;
* On signal act;
* Wait for next incoming observation;

Using dataframes it appeals to me, because i can keep only the strict data for the required window, or instead to make use of the entire data set for strategy debugging purposes. Another appealing advantage is that much of the traditional indicators can be computed easily by pandas with few lines of code.

On the other hand it seemed to me that @mhallsmoore is using a different approach by just keeping minimal/current data, and iterates thru a dictionary of instruments to be traded. 

I am really keen to know what are your opinions on this one, and what design directions will be taken as quite recently i came thru exactly this design decisions!!

Helio

**Comment by mhallsmoore** [comment]
Hi all,

I'm going to be working on an implementation of BarEvent as well as BarPriceHandler (or similar) shortly. Thanks very much for the great suggestions around software architecture and links to papers.

At this stage I'll keep it simple but I imagine we'll want to improve it as time goes on. In particular, Helio's suggestion about using OANDA bid/ask spread within OHLCV events is certainly something that will be added in the future.

If anybody is happy to review the modifications once I've made them, I'll submit it as a Pull Request. Otherwise, I'll simply include it in the repo.

Cheers,

Mike.

**Comment by mhallsmoore** [comment]
I've just added the BarEvent object into the codebase. It contains some of the functionality discussed above in various forms. QSTrader now works with both BarEvent and TickEvent PriceHandler objects. As a test, I've created a MovingAverageCrossStrategy in the examples directory that requires AAPL.csv from Yahoo Finance in order to function.

In time we can add extra functionality, such as proper spread handling for bar data, as per Helio's suggestion.

Ryan - I haven't yet added an Open Timestamp and Close Timestamp, I've simply used the associated "date" from the CSV files, so I should also add this at some stage.

Let me know if you think any improvements are necessary.

**Comment by ryankennedyio** [comment]
@mhallsmoore this is sweet, can't see an immediate need for open/close timestamps. Easy enough to add in later if it's truly required.

**Comment by mhallsmoore** [comment]
Good - I guess we can close this for the time being?

**Comment by ryankennedyio** [comment]
Actually one thing I just remembered thinking about a few weeks ago,

I was kinda wondering if TickEvent and BarEvent could both inherit from the same parent, as that might reduce a tiny bit of code repetition in a few places? For example within the backtester loop

Unsure if it's worth the effort though. Happy to have a play around if you think it could be worth doing.

**Comment by chivalry123** [comment]
Thank you sooo much for the great work.... I am actually using qsforex, and I also want to use the bars for forex trading than ticks (for faster back test smaller data sizes)... Do you think the same change can be applied to qsforex ?
