### ISSUE TITLE
Backtest is completed without showing any graphs

### ISSUE THREAD

**Issue by nervecell23** [mhallsmoore/qstrader#203]
Terminal shows backtest is completed, Sharpe ratio and Max drawdown are given however no graphs (tearsheet) is shown at all. 

The package is installed with Anaconda under OSX.
Config file qstrader.yml contains only two lines indicating CSV_DATA_DIR and OUTPUT_DIR.

What I have done:
1. Install Anaconda
2. Install QSTrader using pip
3. After testing "Buy and Hold" strategy for the first time, it said "Munch" module was missing therefore I installed "Munch" using Anaconda
4. Running "Buy and Hold" again, it said the backtest was completed, it also gave Sharpe ratio and Max drawdown but no graph was shown.

Any suggestion would be appreciated, thanks!

**Comment by dieterjansen** [comment]
Hi nervecell23,

I think this is due to a small change made to qstrader/statistics/tearsheet.py about 20 days ago which changed:

    plt.show()

to:

    plt.show(block=False)

This has the effect of showing the tearsheet but immediately closing the plot window.

To confirm, find where the qstrader tearsheet.py module was installed (I’m not sure where this is with OS.X/Anaconda – with Linux and virtualenv it is usually /home/user/venv/qstraderp3/lib/python3.5/site-packages/qstrader/statistics/tearsheet.py if installed per the instructions) and temporarily change (around line 637):

    plt.show(block=False)

to

    plt.show(block=True)

This should allow you to see at least see the tearsheet and confirm your install is working.

I’m not sure how this will be resolved longer term.

Cheers,
Dieter.



From: nervecell23 
Sent: Wednesday, May 3, 2017 2:10 AM
To: mhallsmoore/qstrader 
Cc: Subscribed 
Subject: [mhallsmoore/qstrader] Backtest is completed without showing any graphs (#203)

Terminal shows backtest is completed, Sharpe ratio and Max drawdown are given however no graphs (tearsheet) is shown at all.

The package is installed with Anaconda under OSX.
Config file qstrader.yml contains only two lines indicating CSV_DATA_DIR and OUTPUT_DIR.

What I have done:

  1.. Install Anaconda 
  2.. Install QSTrader using pip 
  3.. After testing "Buy and Hold" strategy for the first time, it said "Munch" module was missing therefore I installed "Munch" using Anaconda 
  4.. Running "Buy and Hold" again, it said the backtest was completed, it also gave Sharpe ratio and Max drawdown but no graph was shown. 
Any suggestion would be appreciated, thanks!

**Comment by nervecell23** [comment]
Hi Dieter,

Thanks a lot for the help! Yes the graph shows when I change the plt.show() line in the tearsheet.py
Is there any reason why the blocking option is made False? 

Best

**Comment by dieterjansen** [comment]
Hi nervecell23,

Glad that got you going.

The change was made to allow (presumably repeated) runs of the program from the command line without blocking – I assume maybe to tune strategy parameters in multiple backtests under control of a script but it had the unfortunate side effect of invalidating the install and test instructions in the readme.

I suspect that at some time a flag will probably have to be externalised as a parameter in the API so that backtests can be operated in either mode.  Similar comments apply to controlling the saving of the tearsheet to the ~/out directory as a PNG.  Indeed this may already exist and I just don’t understand how to switch it on and off properly.  Unfortunately just a little outside my comfort zone to make such changes.

I’m sure at some stage the APIs and code and examples will all slip back into alignment but its still under development for now.

Cheers, 
Dieter.

**Comment by nervecell23** [comment]
I see, thanks again for the help Dieter!
