### ISSUE TITLE
Feature/discussion: Example strategies for backtests

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#22]
I was thinking about possible example strategies that might be good to ship with QSTrader.

Here are some initial thoughts:
- Moving Average Crossover (DONE)
- Some form of Mean-Reversion, either via "technicals" or via a proper cointegration approach
- Machine learning forecast example, e.g. with Scikit-Learn
- Possibly sentiment analysis? Although this is very data dependent

Suggested strategies should be simple, with few free parameters.

**Comment by ryankennedyio** [comment]
Exploring sentiment analysis would be fun with a lot of the open-source NLP libraries now available.

Guess we'd implement a "NEWS" event that the backtester or live engine could also handle, which could be passed to a strategy in the same way.

Most providers I've seen pass "NEWS" tick events with a simple URL link?

That might lead to something which will have to be tackled eventually; how to run multiple strategies concurrently?

**Comment by mhallsmoore** [comment]
Ryan,

Your last comment is an interesting point actually. In the fund I used to work at the model we used consisted of a top-level portfolio that allocated funds to a set of strategies, with proportionality of funds decided by an additional algorithm.

Some of the strategies would have counteractive orders (e.g. Strat #1 would long a security by a certain amount while Strat #2 would short it by a certain amount) and thus we needed to net out the difference to avoid unnecessary trades (and thus transaction costs).

It does however make it difficult to discuss individual strategy performance and thus it is sometimes best to talk about overall portfolio performance. All prop trading houses have this problem and they often have centralised risk management to make sure the firm itself is not too far long/short in a particular asset or direction.

**Comment by ryankennedyio** [comment]
Great Mike, glad to hear what I was thinking is roughly in line with standard practice.

One thought I had was to allow a reference from a `Position` to a `Strategy`, or vice-versa. This should only be a few lines, which keeps complexity low, and could allow for things like the `RiskManager` to see how much capital is allocated to each strategy just by looping through the `Positions` in the `Portfolio`.

Either way, I guess in the simplest implementation, a backtest or live-loop would be passed a list of Strategies, rather than just one, and pass the events along to each of those strategies. That kind of computation scales out nicely, so Python's multiprocessing would make that quite efficient.

**Comment by femtotrader** [comment]
A simple `PrintStrategy` which will print ticks, bars is also necessary. See https://github.com/mhallsmoore/qstrader/issues/41
