### ISSUE TITLE
Backtesting kalman filter strategy

### ISSUE THREAD

**Issue by chillliang** [mhallsmoore/qstrader#224]
Hi, I tried backtesting the Kalman filter strategy with an apparently incorrect module name. The code is taken from the QuantStart article on Kalman filter:

`from qstrader.strategy import Strategies, DisplayStrategy`
`ImportError: cannot import name Strategies`

However, I can run the example Buy and Hold Strategy just fine. Is there a problem with the module name under qstrader.strategy?

**Comment by mhallsmoore** [comment]
Hi chillliang,

This is actually due to an outdated API for QSTrader. There have been some backward-compatibility breaking modifications made since the article was published. I'm going to go over each article and make the changes in the future.

The main change was to create a TradingSession class and modify the parameters to the derived Backtest class (you can see that in the Buy & Hold strategy example). The idea was to heavily reduce the necessary "boilerplate" code needed to run a basic strategy. That is, QSTrader now uses sensible defaults.

I'll close this issue when I've changed all of the articles.

Cheers,

Mike.
