### ISSUE TITLE
Any examples for develop? 

### ISSUE THREAD

**Issue by bogomazov** [mhallsmoore/qstrader#273]
I am a beginner trader who wants to use the up to date version of the qstrader.
Thank you :)

**Comment by mhallsmoore** [comment]
Hi @bogomazov,

Thank you for showing interest in the new QSTrader version!

We have since carried out work on a new branch called development. It can be found here: https://github.com/mhallsmoore/qstrader/tree/development

This version will be merged into the master branch in the near future, replacing the current version.

If you would like help getting this new version installed, please let us know.

Kind regards,

Mike.
