### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by hlabcd** [mhallsmoore/qstrader#277]
So I manually goes down the list in requirements.txt and use conda install <package-name> to isntall the individual packages one by one.However, I encountered a problem，buy_and_hold_backtest.py，raise ValueError('No objects to concatenate')

ValueError: No objects to concatenate

**Comment by baogorek** [comment]
I'm also getting this error. My pip install failed on the requirements.txt so I too installed a bunch of packages randomly, and finally had to upgrade numpy. Wondering if it's related to versioning.

**Comment by mhallsmoore** [comment]
Hi @hlabcd and @baogorek,

Indeed the issue is that there is no data in the ``~/data`` directory. I agree that the error message is not particularly helpful!

We are taking a different approach in the upcoming development version (https://github.com/mhallsmoore/qstrader/tree/development) to ensure that it will be clear if any data is missing prior to a backtest.

Kind regards,

Mike.
