### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by buginux** [mhallsmoore/qstrader#279]
Hi there.

I've read all the articles in QuantStart.com and really love this project. But I notice that this project hasn't been updated for whole year.  Just want to know does this project still alive.

Is there any update plan for this project latter on.

Thanks.

**Comment by douglaspetrin** [comment]
I would like to know as well, but it seems it's gone.

**Comment by JamesKBowler** [comment]
by the way your title was correct the first time "Is this project still alive?"

**Comment by buginux** [comment]
@JamesKBowler sorry for the mistake, I'm not quite confident with my English, haha.

**Comment by bastulli** [comment]
Big update today!

**Comment by onahkenneth** [comment]
@buginux 
Follow updates on development branch

**Comment by mhallsmoore** [comment]
Hi all,

To answer @buginux's question, yes the project is still alive!

As @onahkenneth mentions the updates are being made to the ``development`` branch (https://github.com/mhallsmoore/qstrader/tree/development). This is because the internals of the software are sufficiently different from the current version that it warranted a significant rewrite.

We are still testing the dev version internally at the moment but as soon as we're confident in the results we will be merging the code to the master branch.

Regards,

Mike.

**Comment by cero1010** [comment]
owesome
