### ISSUE TITLE
what's the difference for master and advanced algorithm branch?

### ISSUE THREAD

**Issue by chloe-wang** [mhallsmoore/qstrader#329]
hi there,

Just want to know why we are maintaining master and advanced algorithm branches at the same time? I guess they are developed for different purposes?

**Comment by mhallsmoore** [comment]
Hi @chloe-wang,

Thanks for your question.

This is because the new version of QSTrader does not support asset short sales yet, while the version in Advanced Algorithmic Trading does. We are planning to include a more realistic approach to margin and asset shorting for the new version.

We have created the branch so that it is straightforward for readers of the book to be able to replicate the results in the book as well as to fix any issues that might arise (e.g. due to Python version changes) in a self-contained manner.

Kind regards,

Mike.

**Comment by chloe-wang** [comment]
Hi @mhallsmoore,

Thanks for your clarifications.
