### ISSUE TITLE
Merge qstrader and qsforex (?)

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#34]
Hello,

I noticed this project (qstrader) only very recently
I was looking at qsforex code and I didn't noticed this project.
It seems that a lot of code is common between these 2 projects
Isn't there a way to merge them (or to have a third project) with common parts
of qstrader and qsforex.

Kind regards

**Comment by mhallsmoore** [comment]
Hi Femtotrader,

The long-term plan is to make QSTrader the only backtesting engine, with QSForex "merging in" as you suggest.

The background to both projects is that I wanted to write a backtesting system around the OANDA API, which is one of the few good algorithmic trading API endpoints that works almost seamlessly with Python. Hence QSForex was born. However, I soon realised that it would be difficult to expand it into other asset classes or brokerages since it was quite strongly coupled to OANDA.

Thus I decided to "start again" by building QSTrader. At this stage QSTrader only contains equities capability, but forex is the next goal. I will likely be using a lot of the QSForex code and then will redirect all current and future users of QSForex to move to QSTrader, thereby continuing with only one project.

Mike.

**Comment by femtotrader** [comment]
Thanks @mhallsmoore for you reply
Roadmap is much clear now!

**Comment by femtotrader** [comment]
A quick short term roadmap might be:

- packaging
- enable continuous integration
- add examples as part of unit tests
- improve configuration through config file
- improve command line tools
- add profiling tools (display number of tick per seconds)
- cleanup
- improve backtest speed (decimal vs float vs integer... and stats)
- ...

Maybe we could turn this repository to an organization (qstraders ?)
