### ISSUE TITLE
No module named qstrader.*

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#4]
Hi Michael,

Running into this in every way I try to go about it; when running `python examples/test_strategy_backtest.py` I'll get:

```
Traceback (most recent call last):
  File "examples/test_strategy_backtest.py", line 3, in <module>
    from qstrader.backtest.backtest import Backtest
ImportError: No module named qstrader.backtest.backtest
```

This happens after setting up virtualenv and doing
`ln -s ~/development/qstrader/ ~/development/qstrader/venv/lib/python2.7/site-packages/qstrader`

I also get the same issues when doing the whole thing from scratch inside a Vagrant box specifically provisioned for this, using either virtualenvwrapper or the other one, which is bizarre. Should the setup be the same as it was for qsforex?

As a side note; I'm very keen to contribute a lot. Standard github etiquette applies (feature discussion in issues, feature branches and pull requests from there) ?

**Comment by ryankennedyio** [comment]
Also tried doing it with Python 3.4 with the same results;

`ln -s ~/development/qstrader/ ~/development/qstrader/venv/lib/python3.4/site-packages/qstrader/`

Sorry if I'm missing something stupid; still pretty fresh to Python

**Comment by mhallsmoore** [comment]
Hi Ryan,

This is certainly a tricky issue!

I just want to check a few things:

* Have you definitely activated the correct virtual environment? i.e. you've typed the equivalent of "source ~/development/qstrader/venv/bin/activate", either in Python 3.4 or 2.7?

* The ~/development/qstrader/ directory on your machine is definitely the directory with backtest/backtest.py underneath it? I.e. ~/development/qstrader/backtest/backtest.py exists?

* I don't think it will be an issue, but I tend to put my virtual environments outside of my app environments (i.e. I have ~/venv/qstrader AND ~/development/qstrader separately). 

If you've done all those things, then I'll keep investigating. However, it should be the same as for qsforex. 

Also, it would be great to have contributions! As you mentioned, feature discussions -> feature branches -> pull requests is a good workflow too.

Cheers,

Mike.

**Comment by ryankennedyio** [comment]
Well, how about that.
Wiped it, started again and followed the instructions from qsforex line for line, seems to be working now!

Might mess around further with setting the project up in a dedicated VM (vagrant, etc) if future dependancies grow beyond simple pip requirements.

Anyway one final thing; `settings.py.example` doesn't appear to be in the repo at this stage.



Thanks again for the detailed reply too. Always a pain and normally the hardest part for some reason...

**Comment by mhallsmoore** [comment]
Ahh yes...I still need to put in the example file! I think there's still an issue for that? 

At this stage I don't see there being too many additional dependencies beyond libraries installed via pip (although things can change, of course!). There might be some issues around using libraries to talk to Interactive Brokers, but we'll see.

I plan on making qstrader itself available via pip, which should certainly make things a lot easier, although it's early days yet. 

One idea I did have, was to create a "simulated data generator" script, so that for those who don't have any available financial data upon first download, they can get started immediately, albeit only with simulated trading.
